---
# tasks file for RouteProcessor
- name: Route has been created
  debug:
    msg: "A Route object has been created and this playbook is doing stuff."

- debug:
    var: ansible_operator_meta

- name: Get Route info
  community.kubernetes.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: "{{ ansible_operator_meta.namespace }}"
    name: "{{ ansible_operator_meta.name }}"
  register: route_data

- debug:
    var: route_data
